# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190627_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_email',
            field=models.BooleanField(default=False, verbose_name='activate email'),
        ),
    ]
