# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-04 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('user', '0004_user_active_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, verbose_name='receiverinfo')),
                ('detail_address', models.CharField(max_length=50, verbose_name='detailaddress')),
                ('zipcode', models.CharField(max_length=6, verbose_name='zipcode')),
                ('tel', models.CharField(max_length=11, verbose_name='phonenum')),
                ('is_delete', models.BooleanField(default=False, verbose_name='check_if_address_is_delete_or_not')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.Areas', verbose_name='city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.Areas', verbose_name='district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.Areas', verbose_name='province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User_address',
                'verbose_name_plural': 'User_address',
                'db_table': 'shanghui_user_address',
            },
        ),
    ]
