# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('user', '0008_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='street_addresses', to='areas.Areas', verbose_name='street'),
        ),
    ]
