# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190708_0633'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='hermit_user_address',
        ),
    ]
