# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190708_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
