# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 11:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190708_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
