# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_auto_20190708_1125'),
        ('user', '0016_library_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_img',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_collect_library_img', to='libraries.library', verbose_name='library'),
        ),
    ]
