# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_library_library_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='library_img',
        ),
    ]
