# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190725_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_library', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
