# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_auto_20190708_1125'),
        ('user', '0020_auto_20190725_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='library',
        ),
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='libraries.library', verbose_name='library'),
        ),
        migrations.DeleteModel(
            name='library',
        ),
    ]
