# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='libraries.library', verbose_name='user_collected_lib'),
        ),
    ]
