# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_auto_20190708_1125'),
        ('user', '0029_remove_user_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collected_library', to='libraries.library', verbose_name='library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_library', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
