# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190730_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_library',
            field=models.BooleanField(default=False, verbose_name='islibraryuser'),
        ),
    ]
