# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-03 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_user_is_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='detail_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zipcode',
        ),
    ]
