# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-14 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20190803_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(default='group1/M00/00/02/wKjTiV1TbM2AZB2bAAANkt5fqtM4440190', max_length=100, verbose_name='img_url'),
        ),
    ]
