# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'library', 'verbose_name_plural': 'library'},
        ),
        migrations.AlterModelTable(
            name='library',
            table='libraries',
        ),
    ]
