# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-31 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190730_1034'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0005_auto_20190708_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='user_collect',
            field=models.ManyToManyField(through='user.collect_library', to=settings.AUTH_USER_MODEL),
        ),
    ]
