# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-01 09:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190730_1034'),
        ('libraries', '0006_library_user_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('own_library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='libUser', to='libraries.library', verbose_name='libUser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
