# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-02 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_libraryuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='lib_img',
        ),
        migrations.AddField(
            model_name='library',
            name='lib_img_url',
            field=models.CharField(max_length=50, null=True, verbose_name='img_url of the lib'),
        ),
        migrations.AddField(
            model_name='library',
            name='lib_license_url',
            field=models.CharField(default='', max_length=50, verbose_name='lib_license_url'),
        ),
        migrations.AlterField(
            model_name='library',
            name='lib_commit',
            field=models.CharField(max_length=300, verbose_name='commit of the lib'),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='own_library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libUser', to='libraries.library', verbose_name='libUser'),
        ),
    ]
