# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-02 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_auto_20190802_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='is_library',
            field=models.BooleanField(default=False, verbose_name='islibraryuser'),
        ),
    ]
