# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-02 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_libraryuser_is_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='is_library',
        ),
    ]
