# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-02 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_remove_libraryuser_is_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user_collect',
            field=models.ManyToManyField(null=True, through='user.collect_library', to=settings.AUTH_USER_MODEL),
        ),
    ]
