# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-02 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_auto_20190802_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user_collect',
            field=models.ManyToManyField(through='user.collect_library', to=settings.AUTH_USER_MODEL),
        ),
    ]
