# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-05 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0013_auto_20190802_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('User_comment', models.CharField(max_length=500)),
                ('User_grade', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='detail_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='grade',
            field=models.FloatField(null=True),
        ),
    ]
