# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-08 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_auto_20190807_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.IntegerField()),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='library_detail_info_page_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_model_views_url', models.CharField(max_length=100)),
                ('page_model', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='lib_imglist_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='lib_info_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
