# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0016_auto_20190808_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='lib_imglist_url',
        ),
        migrations.AlterField(
            model_name='imglist',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
