# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0017_auto_20190808_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='page_mode_id',
            field=models.IntegerField(default=1),
        ),
    ]
