# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0018_library_page_mode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgsave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
