# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-12 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0021_auto_20190809_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='explore_time',
            field=models.IntegerField(default=0),
        ),
    ]
