# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0022_library_explore_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='explore_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.IntegerField()),
                ('explore_data_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='library',
            name='explore_time',
        ),
    ]
